name: active_loan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3
  intl: ^0.17.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  google_fonts: ^3.0.1
  feather_icons: ^1.2.0
  package_info_plus: ^1.4.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  freezed: ^2.0.3+1
  dartz: ^0.10.1
  connectivity_plus: ^2.3.5
  shimmer: ^2.0.0
  flutter_share: ^2.0.0
  open_file: ^3.2.1
  image_picker: ^0.8.5+3
  file_picker: ^4.6.1
  flutter_svg: ^1.1.0
  otp_text_field: ^1.1.2
  flutter_secure_storage: ^5.0.2
  introduction_screen: ^3.0.2
  qr_code_scanner: ^1.0.0
  font_awesome_flutter: ^10.1.0
  visibility_detector: ^0.3.3
  razorpay_flutter: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/googleplayicon-ed.png"
